server:
  port: 8090

logging:
  level:
    root: INFO
    org.springframework.web: trace
    org.springframework.security: trace
    org.springframework.security.oauth2: trace

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://127.0.0.1:9000
